-- Icons used everywhere in the config
-- More: https://www.nerdfonts.com/cheat-sheet

M = {}

M.diagnostics = { -- referenced
    -- BoldError = "",
    Error = "", -- referenced
    BoldWarn = "", -- referenced
    Warn = "", -- referenced
    -- BoldInfo = "",
    Info = "", -- referenced
    -- BoldQuestion = "",
    -- Question = "",
    -- BoldHint = "",
    Hint = "󰌶", -- ""; referenced
    -- Debug = "",
    -- Trace = "✎",
}
M.git = {
    Add = "", -- ""; referenced
    Mod = "", -- ""; referenced
    Remove = "", -- ""; referenced
    Ignore = "",
    Rename = "",
    Diff = "", -- ""
    Repo = "",
    -- FileDeleted = "",
    -- FileIgnored = "◌",
    -- FileRenamed = "",
    -- FileStaged = "S",
    -- FileUnmerged = "",
    -- FileUnstaged = "",
    -- FileUntracked = "U",
    -- Branch = "",
}

--- LSP symbol kinds.
M.kinds = { -- referenced
    Array = "",
    Boolean = "",
    Class = "",
    Color = "",
    Constant = "", -- "", "󰏿"
    Constructor = "", -- "", ""
    Copilot = "",
    Enum = "", -- ""
    EnumMember = "", -- ""
    Event = "", -- ""
    Field = "󰜢", -- ""
    File = "", -- ""
    Folder = "", -- ""
    Function = "󰊕", -- ""
    Interface = "", -- ""
    Key = "",
    Keyword = "󰌋", -- ""
    Misc = "",
    Method = "󰊕", -- ""
    Module = "",
    Namespace = "",
    Null = "󰟢", -- ""
    Number = "",
    Object = "",
    Operator = "󱓉", -- ""
    Package = "", -- ""
    Property = "", -- ""
    Reference = "", -- ""
    Snippet = "", -- "", ""
    String = "", -- ""
    Struct = "", -- ""
    Text = "󰊄", -- "", ""
    TypeParameter = "",
    Unit = "", -- ""
    Value = "󰎠", -- ""
    Variable = "󰀫", -- ""
}
---------------------------------------------------------------------------
M.ui = {
    ArrowCircleDown = "",
    ArrowCircleLeft = "",
    ArrowCircleRight = "",
    ArrowCircleUp = "",
    ArrowClosed = "", -- ""; referenced
    ArrowOpen = "", -- ""; referenced
    ArrowClosedSmall = "", -- referenced
    ArrowOpenSmall = "", -- referenced
    BigCircle = "", -- name: nf-cod-circle_large_filled
    BigUnfilledCircle = "", -- name: nf-cod-circle_large
    BoldArrowDown = "",
    BoldArrowLeft = "",
    BoldArrowRight = "",
    BoldArrowUp = "",
    BoldClose = "",
    BoldDividerLeft = "",
    BoldDividerRight = "",
    BoldLineLeft = "▎", -- referenced
    BookMark = "", -- ""
    BoxChecked = "󰄵", -- ""; referenced
    Bug = "", -- ""; referenced
    Calendar = "", -- ""
    Check = "", -- ""; referenced
    ChevronDown = "",
    ChevronRight = "",
    ChevronShortDown = "",
    ChevronShortLeft = "",
    ChevronShortRight = "",
    Circle = "●", -- referenced
    ChevronShortUp = "",
    Clock = "", -- referenced
    Close = "",
    CloudDownload = "", -- ""
    Code = "", -- ""
    Comment = "",
    Dashboard = "", -- ""
    DashedLine = "┊", -- referenced
    DebugConsole = "",
    DividerLeft = "",
    DividerRight = "",
    DoubleCheck = "", -- referenced
    DoubleChevronRight = "»",
    Ellipsis = "",
    EmptyFolder = "",
    EmptyFolderOpen = "",
    FileSymlink = "",
    Files = "", -- referenced
    FindFile = "󰈞",
    FindText = "󰊄",
    Fire = "", -- ""; referenced
    FolderOpen = "", -- ""
    FolderSymlink = "",
    Forward = "  ", -- referenced
    Gear = "", -- ""; referenced
    GitFolder = "", -- referenced
    History = "",
    Lazy = "󰒲", -- referenced
    Lightbulb = "",
    LineLeft = "▏", -- referenced
    LineMiddle = "│",
    List = "", -- ""; referenced
    Lock = "", -- referenced
    Message = "󰍩", --referenced
    MidCircle = "", -- name: nf-fa-circle
    MidDottedCircle = "", -- name: nf-fa-circle_dot
    MidUnfilledCircle = "", -- name: nf-oct-circle
    NewFile = "", -- ""; referenced
    Note = "",
    NoteBook = "",
    Paragraph = "󰊆",
    Pencil = "",
    Plus = "",
    Project = "", -- ""
    Scopes = "",
    Search = "", -- ""; referenced
    SignIn = "", -- ""
    SignOut = "", -- ""; referenced
    Speedometer = "󰾆", -- "⏲"; referenced
    Stacks = "",
    Tab = "󰌒", -- referenced
    Table = "", -- ""
    Target = "󰀘",
    Telescope = "", -- ""
    Tree = "",
    Triangle = "󰐊",
    TriangleShortArrowDown = "",
    TriangleShortArrowLeft = "",
    TriangleShortArrowRight = "",
    TriangleShortArrowUp = "",
    UnicodeBallotX = "✗", -- referenced
    UnicodeCheck = "✓", -- referenced
    UnicodeCircleArrow = "⟳", -- referenced
    Watches = "󰂥",
}

M.misc = {
    Robot = "",
    Squirrel = "", -- ""
    Tag = "", -- ""
    Vim = "", -- referenced
    Watch = "",
}

return M
